extends: airbnb-base
plugins:
  - import

env:
  mocha: true
  node: true

rules:
  padded-blocks: off
  no-trailing-spaces: [error, skipBlankLines: true]
  comma-dangle: [error, never]

  # Doesn't work in node v4
  strict: off
  prefer-rest-params: off
  prefer-spread: off
